# Generated by Django 4.1.3 on 2023-01-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstnm', models.CharField(max_length=50)),
                ('lastnm', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('mesg', models.TextField()),
            ],
        ),
    ]
